services:
  web:
    container_name: taskforge-web
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    container_name: taskforge-redis
    image: redis:7-alpine
    ports:
      - "6380:6379"

  celery:
    container_name: taskforge-celery
    build: .
    command: celery -A TaskForge worker --loglevel=info
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
      - web
